export const GOALS = [
    { id: 'manage', label: 'To manage my finances' },
    { id: 'track', label: 'To figure out where my money is going' },
    { id: 'goal', label: 'I have goals I want to accomplish' },
    { id: 'explore', label: 'Just looking around' },
];

export const CURRENCIES = [
    { code: 'USD', name: 'US Dollar', country: 'United States', flag: '🇺🇸' },
    { code: 'GBP', name: 'British Pound', country: 'United Kingdom', flag: '🇬🇧' },
    { code: 'EUR', name: 'Euro', country: 'European Union', flag: '🇪🇺' },
    { code: 'NGN', name: 'Naira', country: 'Nigeria', flag: '🇳🇬' },
    { code: 'CAD', name: 'Canadian Dollar', country: 'Canada', flag: '🇨🇦' },
    { code: 'JPY', name: 'Japanese Yen', country: 'Japan', flag: '🇯🇵' },
    { code: 'AUD', name: 'Australian Dollar', country: 'Australia', flag: '🇦🇺' },
    { code: 'CHF', name: 'Swiss Franc', country: 'Switzerland', flag: '🇨🇭' },
    { code: 'CNY', name: 'Chinese Yuan', country: 'China', flag: '🇨🇳' },
    { code: 'INR', name: 'Indian Rupee', country: 'India', flag: '🇮🇳' },
    { code: 'BRL', name: 'Brazilian Real', country: 'Brazil', flag: '🇧🇷' },
    { code: 'MXN', name: 'Mexican Peso', country: 'Mexico', flag: '🇲🇽' },
    {
        code: 'ZAR',
        name: 'South African Rand',
        country: 'South Africa',
        flag: '🇿🇦',
    },
    { code: 'SGD', name: 'Singapore Dollar', country: 'Singapore', flag: '🇸🇬' },
    { code: 'HKD', name: 'Hong Kong Dollar', country: 'Hong Kong', flag: '🇭🇰' },
    { code: 'KRW', name: 'South Korean Won', country: 'South Korea', flag: '🇰🇷' },
    { code: 'SEK', name: 'Swedish Krona', country: 'Sweden', flag: '🇸🇪' },
    { code: 'NOK', name: 'Norwegian Krone', country: 'Norway', flag: '🇳🇴' },
    {
        code: 'NZD',
        name: 'New Zealand Dollar',
        country: 'New Zealand',
        flag: '🇳🇿',
    },
    { code: 'TRY', name: 'Turkish Lira', country: 'Turkey', flag: '🇹🇷' },
    { code: 'RUB', name: 'Russian Ruble', country: 'Russia', flag: '🇷🇺' },
    {
        code: 'AED',
        name: 'UAE Dirham',
        country: 'United Arab Emirates',
        flag: '🇦🇪',
    },
    { code: 'SAR', name: 'Saudi Riyal', country: 'Saudi Arabia', flag: '🇸🇦' },
    { code: 'EGP', name: 'Egyptian Pound', country: 'Egypt', flag: '🇪🇬' },
    { code: 'GHS', name: 'Ghanaian Cedi', country: 'Ghana', flag: '🇬🇭' },
];